server:
  port :80

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb'   # H2 DB ?? ?? (In-Memory Mode)
#    url: 'jdbc:h2:~/test'    # H2 DB ?? ?? (Embedded Mode)
    username: username        # H2 DB ?? ID (??? ??)
    password: password        # H2 DB ?? PW (??? ??)
