version: "3"
services:
  maria-docker:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: simple_auth
      MYSQL_USER: root

  redis-docker:
    image: redis:latest
    command: redis-server --port 6379
    container_name: "docker-redis"
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6379:6379"
networks:
  simple-auth:
    driver: bridge